name: Tests

on:
  push:
    branches:
      - main

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1
  DJANGO_SETTINGS_MODULE: tests.django.settings
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COVERALLS_PARALLEL: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    env:
      COVERALLS_FLAG_NAME: python${{ matrix.python-version }}-${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"

      - name: Load cached venv
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            .venv
            .tox
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-tox-v1

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Install project
        run: poetry install

      - name: Run tox
        run: poetry run tox

      - name: Submit coverage
        run: poetry run coveralls --service=github

  submit-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"

      - name: Load cached venv
        id: cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-cov-v1

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Install project
        run: poetry install

      - name: Finnish coverage report
        run: poetry run coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"

      - name: Load cached venv
        id: cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-docs-v1

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Install project
        run: poetry install

      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force --strict --verbose
