name: Release

on:
  release:
    types:
      - created

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1
  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"

      - name: Load cached venv
        id: cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-release-v1

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-dev --no-root

      - name: Install project
        run: poetry install

      - name: Publish on PyPi
        run: poetry publish --build
